generation:
  sampler:
    name: edm
    num_steps: 56
    sigma_min: 0.002
    sigma_max: 80.0
    rho: 7.0
    S_churn: 2.0
    S_min: 40.0
    S_max: 80
    S_noise: 1.0

  output:
    return_intermediates: false
    ensemble_size: 1